### ISSUE TITLE
Missing selector on Paper Kit 2 (Free version)

### ISSUE THREAD

**Issue by trnelson** [creativetimofficial/paper-kit-2#25]
In the v2.2.0 free version, it appears part of the selector for dropdowns is missing. I compared with the code in the Pro version from the demo page.

On line 62, the selector `$('.navbar-collapse a[data-scroll="true"]')` is missing the `a[data-scroll="true"]` part of the selector, which causes _all_ clicks within the sidebar (including on dropdown lists) to dismiss the sidebar.

Adding the second part of the selector resolves the issue.

**Comment by groovemen** [comment]
Hello @trnelson, 

Thank you for using our products and also for this issue solution. We will fix this issue in the next update. 

Best, 
Stefan
